development:
  adapter: postgresql
  database: language_board_development
  username:
  password:
  host: localhost

test: &TEST
  adapter: postgresql
  database: language_board_test
  username:
  password:
  host: localhost
  min_messages: warning

cucumber:
  <<: *TEST

production:
  adapter: postgresql
  database: language_board_production
  username:
  password:
  host: localhost
